CrudPractica/CrudPractica/Models/ContactoModel.cs
using System.ComponentModel.DataAnnotations;

namespace CrudPractica.Models
{
    public class ContactoModel
    {
        public int Idcontacto { get; set; }
        [Required(ErrorMessage = "El campo Nombre es obligatorio.")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El campo Telefono es obligatorio.")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "El campo Correo es obligatorio.")]
        public string Correo { get; set; }

    }
}

CrudPractica/CrudPractica/Models/ErrorViewModel.cs
namespace CrudPractica.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudPractica/CrudPractica/Controllers/HomeController.cs
using CrudPractica.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudPractica.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudPractica/CrudPractica/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using CrudPractica.Datos;
using CrudPractica.Models;

namespace CrudPractica.Controllers
{
    public class MantenedorController : Controller
    {
        ContactoDatos _contactoDatos = new ContactoDatos();
        public IActionResult Listar()
        {
            //muestra lista de comntactos
            var lista = _contactoDatos.ObtenerLista();
            return View(lista); // el form recibe toda la lista
        }
        public IActionResult Guardar()
        {
            //solo devuelve la vista(formulario html)
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(ContactoModel contacto)
        {
            //recibir un objeto para guardarlo en la bd

            if (!ModelState.IsValid) // si hay un campo obligatorio vacio
                 return View();
  
            var respuesta = _contactoDatos.Guardar(contacto);

            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                return View();
            }
            
        }

        public IActionResult Editar(int Idcontacto)
        {
            //solo devuelve la vista(formulario html)
            var contacto = _contactoDatos.ObtenerContacto(Idcontacto);
            return View(contacto);
        }

        [HttpPost]
        public IActionResult Editar(ContactoModel contacto)
        {
            //metodo que recibe el objeto para poder editarlo
            if (!ModelState.IsValid) // si hay un campo obligatorio vacio
                return View();

            var respuesta = _contactoDatos.Editar(contacto);

            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                return View();
            }
        }

        public IActionResult Eliminar(int Idcontacto)
        {
            //solo devuelve la vista(formulario html)
            var contacto = _contactoDatos.ObtenerContacto(Idcontacto);
            return View(contacto);
        }

        [HttpPost]
        public IActionResult Eliminar(ContactoModel contacto)
        {
            //metodo que recibe el objeto para poder eliminarlo
        
            var respuesta = _contactoDatos.Eliminar(contacto.Idcontacto);

            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                return View();
            }
        }
    }
}

CrudPractica/CrudPractica/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CrudPractica/CrudPractica/Views/Mantenedor/Editar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar Contacto
    </div>
    <div class="card-body">

        <form asp-action="Editar" asp-controller="Mantenedor" method="post">
            <input asp-for="Idcontacto" type="hidden" class="form-control" id="nombre">
            <div class="mb-3">
                <label for="nombre" class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control" id="nombre">
                <span asp-validation-for="Nombre" class="text-danger"></span> <!--muestra mensaje de error que se puso en el model si el espacio se deja en blanco-->
            </div>
            <div class="mb-3">
                <label for="" class="form-label">Telefono</label>
                <input asp-for="Telefono" type="text" class="form-control" id="">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="" class="form-label">Correo</label>
                <input asp-for="Correo" type="email" class="form-control" id="">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

CrudPractica/CrudPractica/Views/Mantenedor/Eliminar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar Contacto
    </div>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">
            <input asp-for="Idcontacto" type="hidden" class="form-control" id="nombre">

            <div class="alert alert-danger" role="alert">
               Desea eliminar al contacto: @Html.DisplayTextFor(m => m.Nombre) ? <!---El dsiplayTextFor sirve para que al atibuto del model al que llame me aparezac en formato texto-->
            </div>
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

CrudPractica/CrudPractica/Views/Mantenedor/Guardar.cshtml
@model ContactoModel // para usar los atributos de el modelo en esta clase por medio de asp-for
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Contacto
    </div>
    <div class="card-body">

        <form asp-action="Guardar" asp-controller="Mantenedor" method="post" >
            <div class="mb-3">
                <label for="nombre" class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control" id="nombre" > 
                <span asp-validation-for="Nombre" class="text-danger"></span> <!--muestra mensaje de error que se puso en el model si el espacio se deja en blanco-->
            </div>
            <div class="mb-3">
                <label for="" class="form-label">Telefono</label>
                <input asp-for="Telefono" type="text" class="form-control" id="">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="" class="form-label">Correo</label>
                <input asp-for="Correo" type="email" class="form-control" id="">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

CrudPractica/CrudPractica/Views/Mantenedor/Listar.cshtml
@model List<ContactoModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
            Lista Contacto
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success"><i class="bi bi-plus-circle"> Crear Nuevo</i></a>
        <hr/>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td>@item.Correo</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" asp-route-Idcontacto="@item.Idcontacto"><i class="bi bi-pencil-square"></i> Editar</a>
                            <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm" asp-route-Idcontacto="@item.Idcontacto"><i class="bi bi-trash"></i> Eliminar</a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
      
    </div>
</div>

CrudPractica/CrudPractica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudPractica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudPractica.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudPractica</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CrudPractica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>